core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),

    path('api/v1/', include('authentication.urls')),
    path('', include('geladinhos.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
]

geladinhos/urls.py
from django.urls import path
from .views import (
    GeladinhoListView, GeladinhoCreateView, GeladinhoDetailView,
    GeladinhoUpdateView, GeladinhoDeleteView,
    GeladinhoListCreateApiView, GeladinhoRetrieveUpdateDestroyApiView,
)

urlpatterns = [
    # Sistema
    path(
        'geladinhos/list/',
        GeladinhoListView.as_view(),
        name='geladinho_list',
    ),
    path(
        'geladinhos/create/',
        GeladinhoCreateView.as_view(),
        name='geladinho_create',
    ),
    path(
        'geladinhos/<int:pk>/detail/',
        GeladinhoDetailView.as_view(),
        name='geladinho_detail',
    ),
    path(
        'geladinhos/<int:pk>/update/',
        GeladinhoUpdateView.as_view(),
        name='geladinho_update',
    ),
    path(
        'geladinhos/<int:pk>/delete/',
        GeladinhoDeleteView.as_view(),
        name='geladinho_delete',
    ),

    # API
    path(
        'api/v1/geladinhos/',
        GeladinhoListCreateApiView.as_view(),
        name='geladinho-list-create-api-view',
    ),
    path(
        'api/v1/geladinhos/<int:pk>',
        GeladinhoRetrieveUpdateDestroyApiView.as_view(),
        name='geladinho-detail-api-view',
    )
]

geladinhos/models.py
from django.db import models


class Geladinho(models.Model):
    flavor = models.CharField(
        max_length=100,
        verbose_name='Sabor',
    )
    quantity = models.IntegerField(
        default=0,
        verbose_name='Quantidade',
    )
    description = models.CharField(
        verbose_name='Descrição',
    )
    cost_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Preço de custo',
    )
    selling_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Preço de Venda',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Criado em',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Atualizado em',
    )

    class Meta:
        ordering = ['-quantity']

    def __str__(self):
        return self.flavor

outflows/models.py
from django.db import models
from geladinhos.models import Geladinho


class Outflow(models.Model):
    geladinho = models.ForeignKey(
        Geladinho,
        on_delete=models.PROTECT,
        related_name='outflows',
    )
    quantity = models.IntegerField(
        verbose_name='Quantidade',
    )
    description = models.TextField(
        verbose_name='descrição'
    )
    selling_price_outflow = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
        verbose_name='Preço de Venda de Saída',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Criado em',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Atualizado em'
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Saída'
        verbose_name_plural = 'Saídas'

    def __str__(self):
        return str(self.geladinho)

geladinhos/forms.py
from django import forms
from .models import Geladinho


class GeladinhoForm(forms.ModelForm):
    class Meta:
        model = Geladinho
        fields = [
            'flavor', 'description', 'cost_price', 'selling_price',
        ]
        widgets = {
            'flavor': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'cost_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'selling_price': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'flavor': 'Sabor',
            'description': 'Descrição',
            'cost_price': 'Preço de Custo',
            'selling_price': 'Preço de Venda',
        }

geladinhos/views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django_filters.rest_framework import DjangoFilterBackend
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, CreateView, DetailView, UpdateView, DeleteView,
)
from rest_framework.generics import (
    ListCreateAPIView, RetrieveUpdateDestroyAPIView,
)

from core import metrics, permissions
from .filters import GeladinhoFilter
from .forms import GeladinhoForm
from .serializers import GeladinhoSerializer
from .models import Geladinho


class GeladinhoListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Geladinho
    template_name = 'geladinho_list.html'
    context_object_name = 'geladinhos'
    paginate_by = 10
    permission_required = 'geladinhos.view_geladinho'  # app.Djangomethod_model

    def get_queryset(self):
        """Filtragem por Nome"""
        queryset = super().get_queryset() # Geladinho objects all
        flavor = self.request.GET.get('flavor')  # ?flavor=****

        if flavor:
            queryset = queryset.filter(flavor__icontains=flavor)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # Contextos da view
        context["geladinho_metrics"] = metrics.get_geladinho_metrics()  # Contextos além da view
        return context


class GeladinhoCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Geladinho
    template_name = 'geladinho_create.html'
    form_class = GeladinhoForm
    success_url = reverse_lazy('geladinho_list')
    permission_required = 'geladinhos.add_geladinho'


class GeladinhoDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Geladinho
    template_name = 'geladinho_detail.html'
    permission_required = 'geladinhos.view_geladinho'


class GeladinhoUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Geladinho
    template_name = 'geladinho_update.html'
    form_class = GeladinhoForm
    success_url = reverse_lazy('geladinho_list')
    permission_required = 'geladinhos.change_geladinho'


class GeladinhoDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Geladinho
    template_name = 'geladinho_delete.html'
    success_url = reverse_lazy('geladinho_list')
    permission_required = 'geladinhos.view_geladinho'


# API VIEWS
class GeladinhoListCreateApiView(ListCreateAPIView):
    filter_backends = [DjangoFilterBackend]
    filterset_class = GeladinhoFilter
    queryset = Geladinho.objects.all()
    serializer_class = GeladinhoSerializer
    permission_classes = [permissions.GlobalDefaultPermission]


class GeladinhoRetrieveUpdateDestroyApiView(RetrieveUpdateDestroyAPIView):
    queryset = Geladinho.objects.all()
    serializer_class = GeladinhoSerializer
    permission_classes = [permissions.GlobalDefaultPermission]

geladinhos/templates/geladinho_create.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h3 class="display-4">Criar Geladinhos</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form" onsubmit="desabilitarBotao()">
                {% csrf_token %}
                {{ form.as_p }}
                <button id="botao-salvar" type="submit" class="btn btn-primary">Salvar Geladinhos</button>
            </form>

            <script>
                function desabilitarBotao() {
                    const botao = document.getElementById('botao-salvar');
                    botao.disabled = true;
                    botao.innerText = "Salvando...";
                }
            </script>
        </div>
    </div>

    <a href="{% url 'geladinho_list' %}" class="btn btn-secondary mt-3">Voltar</a>
</div>
{% endblock content %}

geladinhos/templates/geladinho_delete.html
{% extends "base.html" %}


{% block content %}


<div class="container mt-4">
    <h3 class="display-6">Deletar Geladinho</h3>
    <div class="card">
        <div class="card-body">
            <p class="card-body">Tem certeza que quer excluir o Geladinho de <strong>{{object.name}}</strong>?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Deletar</button>
            </form>
            <a href="{% url 'geladinho_list' %}" class="btn btn-secondary mt-3">Cancelar e voltar para lista de Geladinhos</a>
        </div>
    </div>
</div>


{% endblock content %}

geladinhos/templates/geladinho_detail.html
{% extends "base.html" %}


{% block content %}


    <div class="container mt-4">
        <h3 class="display-6">Detalhes do Geladinho</h3>

        <div class="card">
            <div class="card-body">
                <h3 class="card-title">{{ object.flavor }}</h3>
                <p class="card-text" style="white-space: pre-line;">{{ object.description }}</p>
                <p class="card-text">Preço de Custo: <strong>R$ {{ object.cost_price }}</strong></p>
                <p class="card-text">Preço de Venda: <strong>R$ {{ object.selling_price }}</strong></p>
                <p class="card-text">Quantidade em Estoque: <strong>{{ object.quantity }}</strong></p>
            </div>
        </div>
        <a href="{% url 'geladinho_list' %}" class="btn btn-secondary mt-3">Voltar</a>
    </div>


{% endblock content %}

geladinhos/templates/geladinho_list.html
{% extends "base.html" %}

{% block title %}
OSLO - Gelados
{% endblock title %}

{% block content %}

{% include "components/_geladinho_metrics.html" %}

<div class="mb-4"></div>

<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'geladinho_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="flavor" placeholder="Sabor" value="{{request.GET.flavor}}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    {% if perms.geladinho.add_geladinho %}
    <div class="col-md-6 d-flex justify-content-end align-items-start gap-2">
        <a href="{% url 'geladinho_create' %}" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Adicionar Gelado
        </a>
    {% endif %}
    {% if perms.outflow.add_outflow %}
        <a href="{% url 'outflow_create' %}" class="btn btn-warning">
            <i class="bi bi-arrow-up-right-square"></i> Criar Saída
        </a>
    {% endif %}
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Sabor</th>
                <th>Preço de Venda</th>
                <th>Quantidade</th>
                <th>Ações</th>
            </tr>
        </thead>
            {% for geladinho in geladinhos %}
            <tr>
                <td>{{geladinho.id}}</td>
                <td>{{geladinho.flavor}}</td>
                <td>{{geladinho.selling_price}}</td>
                <td>{{geladinho.quantity}}</td>
                <td>
                    
                    <a href={% url 'geladinho_detail' geladinho.id %} class="btn btn-info btn-sm">
                        <i class="bi bi-eye"></i>
                    </a>

                    {% if perms.geladinhos.change_geladinho %}
                    <a href={% url "geladinho_update" geladinho.id %} class="btn btn-warning btn-sm">
                        <i class="bi bi-pencil"></i>
                    </a>
                    {% endif %}

                    {% if perms.geladinhos.delete_geladinho %}
                    <a href={% url "geladinho_delete" geladinho.id %} class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                    {% endif %}

                </td>
            </tr>
            {% endfor %}
        <tbody>

        </tbody>
    </table>
</div>


{% include "components/_pagination.html" %}

{% endblock content %}

geladinhos/templates/geladinho_update.html
{% extends "base.html" %}


{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Editar Geladinho</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">
                    Salvar Geladinho
                </button>
            </form>
        </div>
    </div>
    <a href="{% url 'geladinho_list' %}" class="btn btn-secondary mt-3">Voltar à lista</a>
</div>



{% endblock content %}