core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),

    path('api/v1/', include('authentication.urls')),
    path('', include('geladinhos.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
]

geladinhos/models.py
from django.db import models


class Geladinho(models.Model):
    flavor = models.CharField(
        max_length=100,
        verbose_name='Sabor',
    )
    quantity = models.IntegerField(
        default=0,
        verbose_name='Quantidade',
    )
    description = models.CharField(
        verbose_name='Descrição',
    )
    cost_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Preço de custo',
    )
    selling_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Preço de Venda',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Criado em',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Atualizado em',
    )

    class Meta:
        ordering = ['-quantity']

    def __str__(self):
        return self.flavor

inflows/models.py
from django.db import models
from geladinhos.models import Geladinho


class Inflow(models.Model):
    geladinho = models.ForeignKey(
        Geladinho,
        on_delete=models.PROTECT,
        related_name='inflows',
    )
    quantity = models.IntegerField(
        verbose_name='Quantidade',
    )
    manufacturing_date = models.DateTimeField(
        verbose_name='Data de Fabricacao',
        null=True,
        blank=True,
    )
    description = models.TextField(
        verbose_name='descrição'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Criado em',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Atualizado em'
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'

    def __str__(self):
        return str(self.geladinho)

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import metrics
import json


@login_required(login_url='login')
def home(request):
    geladinho_metrics = metrics.get_geladinho_metrics()
    sales_metrics = metrics.get_sales_metrics()
    daily_sales_data = metrics.get_daily_sales_data()
    daily_sales_quantity_data = metrics.get_daily_sales_quantity_data()
    graphic_geladinho_flavor_metric, geladinho_colors = metrics.get_graphic_geladinho_flavor_metric()

    context = {
        'geladinho_metrics': geladinho_metrics,
        'sales_metrics': sales_metrics,
        'daily_sales_data': json.dumps(daily_sales_data),
        'daily_sales_quantity_data': json.dumps(daily_sales_quantity_data),
        'geladinho_count_by_flavor': json.dumps(graphic_geladinho_flavor_metric),
        'geladinho_colors': geladinho_colors,
    }

    return render(request, 'home.html', context)

outflows/views.py
# Django
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
)
# Django Filters
from django_filters.rest_framework import DjangoFilterBackend
# Django REST Framework
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveAPIView,
)

# Core / projeto
from core import metrics, permissions

# App local
from .forms import OutflowForm
from .models import Outflow
from .serializers import OutflowSerializer
from .filters import OutflowFilter


class OutflowListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Outflow
    template_name = 'outflow_list.html'
    context_object_name = 'outflows'
    paginate_by = 10
    permission_required = 'outflows.view_outflow'

    def get_queryset(self):
        """Filtragem por Nome"""
        queryset = super().get_queryset().select_related('geladinho')
        geladinho = self.request.GET.get('geladinho')

        if geladinho:
            queryset = queryset.filter(geladinho__flavor__icontains=geladinho)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sales_metrics'] = metrics.get_sales_metrics()
        return context


class OutflowCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Outflow
    template_name = 'outflow_create.html'
    form_class = OutflowForm
    success_url = reverse_lazy('outflow_list')
    permission_required = 'outflows.add_outflow'


class OutflowDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Outflow
    template_name = 'outflow_detail.html'
    permission_required = 'outflows.detail_outflow'


# API
class OutflowListCreateApiView(ListCreateAPIView):
    filter_backends = [DjangoFilterBackend]
    filterset_class = OutflowFilter
    queryset = Outflow.objects.all()
    serializer_class = OutflowSerializer
    permission_classes = [permissions.GlobalDefaultPermission]

    # @method_decorator(cache_page(60 * 15, key_prefix='outflow_list'))
    # def list(self, request, *args, **kwargs):
    #     return super().list(request, *args, **kwargs)


class OutflowRetrieveApiView(RetrieveAPIView):
    queryset = Outflow.objects.all()
    serializer_class = OutflowSerializer
    permission_classes = [permissions.GlobalDefaultPermission]

core/templates/components/_footer.html
<footer class="footer mt-auto py-3 text-center">
  <div class="container border-top pt-3">
    <span class="text-muted">© OSLO Geladinhos LTDA</span>
  </div>
</footer>

core/templates/components/_geladinho_metrics.html
<div class="card mt-4">

    <div class="card-body">

        <div class="row">

            <div class="col-md-3">
                <div class="card bg-primary">
                    <div class="card-body">
                        <h5 class="card-title">Quantidade de Gelados</h5>
                        <p class="card-text text-white font-weight-bold display-6">{{geladinho_metrics.total_quantity }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-danger">
                    <div class="card-body">
                        <h5 class="card-title">Custo de Estoque</h5>
                        <p class="card-text text-white font-weight-bold display-6">R${{geladinho_metrics.total_cost_price }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-success">
                    <div class="card-body">
                        <h5 class="card-title">Valor do Estoque</h5>
                        <p class="card-text text-white font-weight-bold display-6">R${{geladinho_metrics.total_selling_price }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-warning ">
                    <div class="card-body">
                        <h5 class="card-title">Lucro de Estoque</h5>
                        <p class="card-text text-white font-weight-bold display-6">R${{geladinho_metrics.total_profit }}</p>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

core/templates/components/_header.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href={% url "home" %}>Oslo Gelados - FreezerStock</a>
  </div>
</nav>

core/templates/components/_pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      
      {# Botões de Primeira e Anterior #}
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Primeira</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        </li>
      {% endif %}

      {# Números das páginas (com range de -3 até +3 da atual) #}
      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {# Botões de Próxima e Última #}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última</a>
        </li>
      {% endif %}
      
    </ul>
  </nav>
{% endif %}

core/templates/components/_sales_metrics.html
<div class="card mt-4">

    <div class="card-body">

        <div class="row">

            <div class="col-md-3">
                <div class="card bg-primary">
                    <div class="card-body">
                        <h5 class="card-title">Quantidade de vendas</h5>
                        <p class="card-text text-white font-weight-bold display-6">{{sales_metrics.total_sales }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-danger">
                    <div class="card-body">
                        <h5 class="card-title">Geladinhos vendidos</h5>
                        <p class="card-text text-white font-weight-bold display-6">{{ sales_metrics.total_geladinhos_sold }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-success">
                    <div class="card-body">
                        <h5 class="card-title">Valor das vendas</h5>
                        <p class="card-text text-white font-weight-bold display-6">R${{ sales_metrics.total_sales_value }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="card bg-warning ">
                    <div class="card-body">
                        <h5 class="card-title">Lucro das vendas</h5>
                        <p class="card-text text-white font-weight-bold display-6">R${{ sales_metrics.total_sales_profit }}</p>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

core/templates/components/_sidebar.html
{% load static %}

<div class="row flex-nowrap">
  <div class="col-auto col-md-0 col-xl-0 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white">
      <button class="btn btn-dark d-block d-sm-none mb-3" type="button" data-bs-toggle="collapse"
        data-bs-target="#menuCollapse" aria-expanded="false" aria-controls="menuCollapse">
        <i class="bi bi-list fs-4"></i>
      </button>
      <div class="collapse d-sm-block" id="menuCollapse">
        <ul class="nav flex-column align-items-start" id="menu">
          <li>
            <a href={% url "home" %} class="nav-link px-0 align-middle {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
              <i class="bi bi-speedometer2 fs-4"></i>
              <span class="ms-1">Dashboard</span>
            </a>
          </li>
          {% if perms.geladinhos.view_geladinho %}
          <li>
            <a href={% url 'geladinho_list' %} class="nav-link px-0 align-middle {% if request.resolver_match.url_name == 'geladinho_list' %}active{% endif %}">
              <i class="bi bi-box-seam fs-4"></i>
              <span class="ms-1">Geladinhos</span>
            </a>
          </li>
          {% endif %}
          {% if perms.inflows.view_inflow %}
          <li>
            <a href={% url 'inflow_list' %} class="nav-link px-0 align-middle {% if request.resolver_match.url_name == 'inflow_list' %}active{% endif %}">
              <i class="bi bi-arrow-down-left-square fs-4"></i>
              <span class="ms-1">Entradas</span>
            </a>
          </li>
          {% endif %}
          {% if perms.outflows.view_outflow %}
          <li>
            <a href="{% url 'outflow_list' %}" class="nav-link px-0 align-middle {% if request.resolver_match.url_name == 'outflow_list' %}active{% endif %}">
              <i class="bi bi-arrow-up-right-square fs-4"></i>
              <span class="ms-1">Saídas</span>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            {% if user.is_authenticated %}
              <form action="{% url 'logout' %}" method="post" id="logout-form" class="nav-link px-0 align-middle">
                {% csrf_token %}
                <button type="submit" class="btn btn-link text-decoration-none text-reset nav-link px-0 align-middle">
                  <i class="bi bi-box-arrow-right fs-4 align-middle"></i>
                  <span class="ms-1 align-middle">Sair</span>
                </button>
              </form>
            {% endif %}
          </li>
        </ul>
      </div>
      <hr>
    </div>
  </div>